# Matrices Theory

<!--
import data_analytics.github as github
print(github.create_jupyter_notebook_header("marcocrowe", "learn-computer-mathematics", "set-theory.ipynb", "master"))
-->
<table style="margin: auto;"><tr><td><a href="https://mybinder.org/v2/gh/marcocrowe/learn-computer-mathematics/master?filepath=set-theory.ipynb" target="_parent"><img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/></a></td><td>online editors</td><td><a href="https://colab.research.google.com/github/marcocrowe/learn-computer-mathematics/blob/master/set-theory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a></td></tr></table>


## Exercises

Given the following sets:

In [4]:
from numpy import array, dot, linalg
from pprint import pprint

In [2]:
A = array([[9, 2, 3], [4, -7, 1]])

In [3]:
print(A)

[[ 9  2  3]
 [ 4 -7  1]]


$A=\begin{bmatrix} 9 & 2 & 3\\ 4 & -7 & 1\end{bmatrix}$

To get the transpose of a matrix, we switch the row and column indices of the matrix. That is, the first row becomes the first column, the second row becomes the second column, and the third row becomes the third column. The transpose of A is denoted as $A^T$.

Transpose of A:

$A^T=\begin{bmatrix} 9 & 4\\ 2 & -7\\ 3 & 1\end{bmatrix}$

In [4]:
arr1_transpose = A.transpose()

print(f"Transposed Array:\n{arr1_transpose}")

Transposed Array:
[[ 9  4]
 [ 2 -7]
 [ 3  1]]


Determinant 

Given $A = [\begin{bmatrix} 2 & −4\\5 & 1\end{bmatrix}]$ and $B = [\begin{bmatrix} 5 & 2\\3 & −6\end{bmatrix}]$ show that $|AB| = |A|.|B|$

Show that |AB| = |A|.|B|

To calculate the determinant of a 2x2 matrix, we use the following formula:

$|A| = \begin{bmatrix} a & b\\ c & d\end{bmatrix} = ad - bc$

$|A| = \begin{bmatrix} 2 & -4\\ 5 & 1\end{bmatrix} = 2*1 - (-4*5) = 2 + 20 = 22$

$|B| = \begin{bmatrix} 5 & 2\\ 3 & -6\end{bmatrix} = 5*-6 - 2*3 = -30 - 6 = -36$

AB = $\begin{bmatrix} 2 & -4\\ 5 & 1\end{bmatrix} * \begin{bmatrix} 5 & 2\\ 3 & -6\end{bmatrix}$

AB = $\begin{bmatrix} 2*5 + (-4)*3 & 2*2 + (-4)*(-6)\\ 5*5 + 1*3 & 5*2 + 1*(-6)\end{bmatrix}$

AB = $\begin{bmatrix} 10 - 12 & 4 + 24\\ 25 + 3 & 10 - 6\end{bmatrix}$

AB = $\begin{bmatrix} -2 & 28\\ 28 & 4\end{bmatrix}$

$|AB| = \begin{bmatrix} -2 & 28\\ 28 & 4\end{bmatrix} = -2*4 - 28*28 = -8 - 784 = -792$

Where a, b, c, and d are the elements of the matrix.

In [5]:
A = array([[2, -4], [5, 1]])
B = array([[5, 2], [3, -6]])

AB = dot(A, B)

In [6]:
print(AB)

[[-2 28]
 [28  4]]


In [7]:
print(f"|A| = {linalg.det(A):.0f}")

print(f"|B| = {linalg.det(B):.0f}")
print(f"|AB| = {linalg.det(AB):.0f}")
print(f"|A| * |B| = {linalg.det(A) * linalg.det(B):.0f}")

|A| = 22
|B| = -36
|AB| = -792
|A| * |B| = -792


In [8]:
if A.shape[0] == B.shape[0] and A.shape[1] == B.shape[1]:
    print("Matrices are compatible for multiplication")
else:
    print("Matrices are not compatible for multiplication")

Matrices are compatible for multiplication


## Paper 2021/2022 Summer

Certainly! Here's the provided questions formatted in Markdown with LaTeX equations:

1. Given the following matrices:
    $$
    A = \begin{bmatrix} 5 & -6 \\ 3 & 2 \\ -7 & 4 \end{bmatrix}, \quad
    B = \begin{bmatrix} 9 & 2 & 3 \\ 4 & -7 & 1 \end{bmatrix}, \quad
    C = \begin{bmatrix} 4 & 5 & 8 \\ -2 \end{bmatrix}, \quad
    D = \begin{bmatrix} 5 & 7 \\ -1 & 3 \\ 6 & 2 \end{bmatrix}
    $$
    1. Find $3B - 2D$
    2. Find $B^T$
2. Given:
    $$
    A = \begin{bmatrix} 2 & -4 \\ 5 & 1 \end{bmatrix}, \quad
    B = \begin{bmatrix} 5 & 2 & 3 \\ -6 \end{bmatrix}
    $$
    Show that $|AB| = |A| \cdot |B|$


Given:
$$
X = \begin{bmatrix} -2 & 3 & 5 \\ 4 & 1 & 7 \\ -6 & 0 & 3 \end{bmatrix}
$$

Find $|X|$, the determinant of $X$.


Rule is: $$|A| = \text{det} \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix} = a\begin{vmatrix} e & f \\ h & i \end{vmatrix} - b\begin{vmatrix} d & f \\ g & i \end{vmatrix} + c\begin{vmatrix} d & e \\ g & h \end{vmatrix} $$

$$ => a(e*i − f*h) − b(d*i − f*g) + c(d*h − e*g)$$


Substitute the values into the formula:  
$ a = -2, b = 3, c = 5, d = 4, e = 1, f = 7, g = -6, h = 0, i = 3 $  
$ |X| = a(e*i − f*h) − b(d*i − f*g) + c(d*h − e*g)$  
$ |X| = -2(1*3 - 7*0) - 3(4*3 - 7*-6) + 5(4*0 - 1*-6) $  
$ |X| = -2(3) - 3(12 + 42) + 5(0 + 6) $  
$ |X| = -6 - 3(54) + 5(6) $  
$ |X| = -6 - 162 + 30 $  
$ |X| = -138 $

$$ \begin{bmatrix} -2 & 3 & 5 \\ 4 & 1 & 7 \\ -6 & 0 & 3 \end{bmatrix} = -2\begin{vmatrix} 1 & 7 \\ 0 & 3 \end{vmatrix} - 3\begin{vmatrix} 4 & 7 \\ -6 & 3 \end{vmatrix} + 5\begin{vmatrix} 4 & 1 \\ -6 & 0 \end{vmatrix} 


In [32]:
matrix_x = array([[-2, 3, 5], [4, 1, 7], [-6, 0, 3]])
print("x=")
print(matrix_x)
print()
print(f"|X| = {linalg.det(matrix_x):.0f}")

x=
[[-2  3  5]
 [ 4  1  7]
 [-6  0  3]]

|X| = -138


Author <a href="https://github.com/marcocrowe" target="_parent">Mark Crowe</a> &copy; 2024. All rights reserved.