Given the following sets

# Matrices Theory

<!--
import data_analytics.github as github
print(github.create_jupyter_notebook_header("marcocrowe", "learn-computer-mathematics", "set-theory.ipynb", "master"))
-->
<table style="margin: auto;"><tr><td><a href="https://mybinder.org/v2/gh/marcocrowe/learn-computer-mathematics/master?filepath=set-theory.ipynb" target="_parent"><img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/></a></td><td>online editors</td><td><a href="https://colab.research.google.com/github/marcocrowe/learn-computer-mathematics/blob/master/set-theory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a></td></tr></table>


## Exercises

Given the following sets:

In [13]:
from numpy import array, dot, linalg

In [5]:
A = array([[9, 2, 3], [4, -7, 1]])

In [6]:
print(A)

[[ 9  2  3]
 [ 4 -7  1]]


$A=\begin{bmatrix} 9 & 2 & 3\\ 4 & -7 & 1\end{bmatrix}$

To get the transpose of a matrix, we switch the row and column indices of the matrix. That is, the first row becomes the first column, the second row becomes the second column, and the third row becomes the third column. The transpose of A is denoted as $A^T$.

Transpose of A:

$A^T=\begin{bmatrix} 9 & 4\\ 2 & -7\\ 3 & 1\end{bmatrix}$

In [7]:
arr1_transpose = A.transpose()

print(f"Transposed Array:\n{arr1_transpose}")

Transposed Array:
[[ 9  4]
 [ 2 -7]
 [ 3  1]]


Determinant 

Given $A = [\begin{bmatrix} 2 & −4\\5 & 1\end{bmatrix}]$ and $B = [\begin{bmatrix} 5 & 2\\3 & −6\end{bmatrix}]$ show that $|AB| = |A|.|B|$

Show that |AB| = |A|.|B|

To calculate the determinant of a 2x2 matrix, we use the following formula:

$|A| = \begin{bmatrix} a & b\\ c & d\end{bmatrix} = ad - bc$

$|A| = \begin{bmatrix} 2 & -4\\ 5 & 1\end{bmatrix} = 2*1 - (-4*5) = 2 + 20 = 22$

$|B| = \begin{bmatrix} 5 & 2\\ 3 & -6\end{bmatrix} = 5*-6 - 2*3 = -30 - 6 = -36$

AB = $\begin{bmatrix} 2 & -4\\ 5 & 1\end{bmatrix} * \begin{bmatrix} 5 & 2\\ 3 & -6\end{bmatrix}$

AB = $\begin{bmatrix} 2*5 + (-4)*3 & 2*2 + (-4)*(-6)\\ 5*5 + 1*3 & 5*2 + 1*(-6)\end{bmatrix}$

AB = $\begin{bmatrix} 10 - 12 & 4 + 24\\ 25 + 3 & 10 - 6\end{bmatrix}$

AB = $\begin{bmatrix} -2 & 28\\ 28 & 4\end{bmatrix}$

$|AB| = \begin{bmatrix} -2 & 28\\ 28 & 4\end{bmatrix} = -2*4 - 28*28 = -8 - 784 = -792$

Where a, b, c, and d are the elements of the matrix.

In [15]:
A = array([[2, -4], [5, 1]])
B = array([[5, 2], [3, -6]])

AB = dot(A, B)

In [16]:
print(AB)

[[-2 28]
 [28  4]]


In [27]:
print(f"|A| = {linalg.det(A):.0f}")

print(f"|B| = {linalg.det(B):.0f}")
print(f"|AB| = {linalg.det(AB):.0f}")
print(f"|A| * |B| = {linalg.det(A) * linalg.det(B):.0f}")

|A| = 22
|B| = -36
|AB| = -792
|A| * |B| = -792


1. $A\cap B$ (2 marks)
2. $U – (A \cup C)$ (3 marks)
3. $|A|$ (2 marks)
4. $(A \cup C) – B$ (3 marks)
5. Is $(B ∩ C) ⊂ A$ Justify your answer.

In [2]:
print("1. A ∩ B =", A & B)
print("2. U – (A ∪ C) =", U - (A | C))
print("3. |A| =", len(A))
print("4. (A ∪ C) – B =", (A | C) - B)

print("5:")
print("B | C =", B | C)
print("A =", A)
print((B | C).issubset(A))
print("5. ", "(B ∪ C) ⊆ A =" if (B | C).issubset(A) else "(B ∪ C) ⊈ A =")

1. A ∩ B = {10, 12, 14}
2. U – (A ∪ C) = {1, 3, 5, 7, 9, 11, 13, 17}
3. |A| = 7
4. (A ∪ C) – B = {2, 4, 6, 8, 18, 19, 20}
5:
B | C = {10, 11, 12, 13, 14, 15, 16, 18, 19, 20}
A = {2, 4, 6, 8, 10, 12, 14}
False
5.  (B ∪ C) ⊈ A =


Author <a href="https://github.com/marcocrowe" target="_parent">Mark Crowe</a> &copy; 2024. All rights reserved.